vastlimits/uberAgent-config

rules/uberAgent-ESA-am-vastlimits.conf

Dns exfiltration

---

rules/uberAgent-ESA.conf

Updated the main ESA configuration file to contain all theoretically available combinations. The adapted sigma converter will generate empty files in case of unavailable rules.

Add missing file names.

---

rules/uberAgent-ESA-am-vastlimits.conf

This PR re-applies all changes that were lost during repository setup.

Re-apply changes that were lost during repository setup.

---

rules/uberAgent-eventdata-filter-vastlimits-macOS.conf

Add the missing configuration file for macOS.

Add missing configuration file for macOS.

---

rules/uberAgent-eventdata-filter-vastlimits-macOS.conf

Add the missing configuration file for macOS.

Add missing configuration file.

---

rules/uberAgent-eventdata-filter-vastlimits-DNS.conf
rules/uberAgent-eventdata-filter-vastlimits-Windows.conf
rules/uberAgent-eventdata-filter.conf

- New config file uberAgent-eventdata-filter-vastlimits-DNS.conf
- Various additional exclusions for domains deemed safe

Additional DNS query exclusions

---

convert-sigma-rules.sh

git config returns 1 for the case that no files has been changed.

Ignore error code

---

rules/uberAgent-eventdata-filter-vastlimits-DNS.conf

I855: Ignore well known DNS queries.

I855: Ignore well known DNS queries.

---

.github/workflows/CreateArchive.yml

Note: the workflow doesn't show up in the UI's Actions tab. According to [this SO answer](https://stackoverflow.com/a/71423764/234152) this is because the YML is not in the `main` branch yet.

Added workflow to create a config archive

---

config/uberAgent-data-volume-optimized.conf
config/uberAgent.conf

This commit adds the options "Hotplug" and "Monitor" to the stanza "FilesystemMonitoring" in the relevant configuration files.

Add new options for filesystem monitoring.

---

convert-sigma-rules.sh

This PR fixes the Sigma rule generation pipeline.

Updated paths.

---

config/uberAgent-data-volume-optimized.conf
config/uberAgent.conf

This pull request updates the descriptions for filesystem monitoring options.

Update description for filesystem monitoring options.

---

.github/workflows/DailyTask.yml

Create the daily files at 0:00 UTC.

Create rules at 0:00 UTC.

---

config/uberAgent-data-volume-optimized.conf
config/uberAgent.conf

This PR adds the new WMI Provider configuration to the .conf files.

WMI Provider configuration

---

config-dev/Security inventory/Windows/Service/WindowsServices.ps1

C:\Windows is an uncommon location

Fixed description

---

config/uberAgent-data-volume-optimized.conf
config/uberAgent.conf

Move ConfigChangeRestartTimeoutSec to [Configuration_Settings] stanza.
Add Version to [Configuration_Settings] stanza.
Clarify doc-string on ConfigCachePollInterval.

Move ConfigChangeRestartTimeoutSec from [Misc] to [Configuration_Setings]

---

config-dev/Security inventory/Windows/Service/WindowsServices.ps1

- Added excludes for internal Windows services

Added excludes

---

config-dev/Security inventory/Windows/Certificate/Certificate-Machine.ps1
config-dev/Security inventory/Windows/Certificate/Certificate-User.ps1
config-dev/Security inventory/Windows/Shared/Helper.ps1

Added better $null and empty handling

Added better $null and empty handling

---

config/uberAgent-ESA-am-vastlimits.conf
config/uberAgent-eventdata-filter-vastlimits-Windows.conf

This commit changes the syntax for regular expressions to the new optimized variant.

B568: Update regular expression syntax.

---

.github/workflows/ValidateConfigFilesConsistency.yml
config/uberAgent-data-volume-optimized.conf
config/uberAgent.conf

Added action that checks the consistency of both configuration files (uberAgent.conf and uberAgent-data-volume-optimized.conf)

Added Azure Event Hubs as receiver

---

config/uberAgent-ESA-si-vastlimits-macos.conf

This PR updates the macOS SCI template configuration file to include the tests for local users in the corresponding timer.

B801: update macOS SCI template conf

---

config-dev/Security inventory/macOS/NetworkConfiguration/NetworkConfiguration.zsh

This PR adds error handling for devices without WiFi adapters (e.g., virtual machines). This case is currently not handled correctly so the script output becomes invalid.

B803: fix error handling for devices without WiFi adapters

---

config/uberAgent-data-volume-optimized.conf
config/uberAgent.conf

Link to our documentation in the configuration files.

Add documentation link for Azure Data Explorer / EventHubs

---

.github/workflows/Sigma.yml

This PR adds uberAgent 7.2 to daily rule generation.

Devops: Add uberAgent 7.2 to daily rule generation.

---

.github/workflows/CreateArchive.yml

This PR enables uberAgent archive creation for 7.2.

Enable uberAgent archive creation for 7.2

---

.github/workflows/CreateArchive.yml
.github/workflows/ValidateConfig.yml

Prepare archive creation on version/7.2.1.

Prepare archive creation on version/7.2.1

---

config/uberAgent.conf

add config for blocked exec collection

add blocked exec config

---

config/uberAgent-ESA-am-vastlimits.conf
config/uberAgent-data-volume-optimized.conf
config/uberAgent.conf

- Replace `ActivityMonitoringRule` with `ThreatDetectionRule`
- Replace `ActivityMonitoringRule_Filter` with `ThreatDetectionRule_Filter`
- Replace `AddActivityMonitoringExpression` with `AddThreatDetectionExpression`

Change old Activity Monitoring stanza to ThreatDetection stanza variants.

---

.github/workflows/Configuration.yml

Fixup pipeline regression on develop

Fixup pipeline regression on develop

---

config/uberAgent-eventdata-filter-vastlimits-Windows.conf

This mapping is performed through uberAgent itself.

B993: Configuration changes due to uberAgent AppId changes.

---

.github/workflows/Configuration.yml

Enable configuration-pipeline for branch `hotfix/7.3.1`.

Update configuration-pipeline for version 7.3.1

---

config/uberAgent-data-volume-optimized.conf
config/uberAgent-eventdata-filter-vastlimits-Windows.conf
config/uberAgent.conf

Cherry pick B993, B996 that are relevant for 7.4.

Cherry pick from previous hotfix 7.3.1

---

config/uberAgent-data-volume-optimized.conf
config/uberAgent.conf

This PR adds missing cherry-picks to `version/7.4`.

I1329: Devops: Update version/7.4 branch

---

config/uberAgent-data-volume-optimized.conf
config/uberAgent.conf

Added configuration option `uberAgent` to WmiProvider

Added option `uberAgent` to WmiProvider

---

config/uberAgent-data-volume-optimized.conf
config/uberAgent.conf

 I1396: split azure event hubs message if too big
