convert-sigma-rules.sh
This commit should hotfix the current parser crash due to missing CIDR modifier implementation.
=> Hotfix the current parser crash due to missing CIDR modifier.

convert-sigma-rules.sh
Uses legacy-sigmatools as base reference for the sigma compiler and fetches the daily rules from the main repository to fixup the pipeline.
Fixed pipeline result in my fork: 
- https://github.com/svnscha/uberAgent-config/actions/runs/4744709415
=> Use legacy-sigmatools

config/uberAgent-remote-config-macOS.conf
To keep the wording across platforms consistent, the configuration option for specifying the path to the configuration archive under macOS was renamed to match the Windows client's terminology.
=> Rename configuration option to match wording on Windows.

config-dev/Security inventory/Windows/Antivirus/Antivirus.ps1, config-dev/Security inventory/Windows/Firewall/Firewall.ps1, config-dev/Security inventory/Windows/LocalUserAndGroups/LocalUsersAndGroups-Machine.ps1, config-dev/Security inventory/Windows/LocalUserAndGroups/LocalUsersAndGroups-User.ps1, config-dev/Security inventory/Windows/Shared/Helper.ps1
Enums under PowerShell 3.0 and 4.0 can only be declared via .Net. However, this would require further security customizations, which is why I have now changed the ENUM's to hashtabs and built corresponding helpers. This leads to the fact that we do not need .NET code.
=> Fixed config problems

convert-sigma-rules.sh
This rule breaks the current converter. Exclude it as long as we have not yet updated the sigma toolchain. 
- Verified in my fork: https://github.com/svnscha/uberAgent-config/actions/runs/5948020243/job/16131033807
=> Remove ./sigma/rules/web/proxy_generic/proxy_webdav_search_ms.yml

Tools/InvokeuberAgentConfigDownload/InvokeuberAgentConfigDownload.ps1
The `git clone` command could brake on mediocre networks. Added `--depth 1` to the command, as we don't need the complete git history, but only the files of the latest snapshot.
=> Added git clone depth 1

.github/workflows/Sigma.yml
Use test.pypi.org repository for `develop`-branch rules so that we can use the current in-development version of pySigma-backend-uberAgent.
=> Use test.pypi.org repository for develop rules.

config/uberAgent.conf
This PR adds the macOS-specific option "EnableCdHash" to the stanza "ProcessStartupSettings". It enables/disables the collection of an application's/processes code directory hash.
=> macOS: add option EnableCdHash

.github/workflows/CreateArchive.yml
In the CreateArchive-pipeline:
- use double quotes in the file-filter of the "download dll"-step
- use consistent spelling for the supplied environment variables
=> Fix typo in the CreateArchive-pipeline

.github/workflows/CreateArchive.yml, .github/workflows/ValidateConfig.yml
- Prevent the ValidateConfig-workflow from running on development branches.
- Restrict the CreateArchive workflow only to the develop- and version/7.1 branches.
This is due to the need to manually juggle OIDC for development branches.
=> Exclude the configuration-check workflow from working branches

config-dev/Security inventory/macOS/Utils.zsh
Remove the logic that chooses between the available `jq(1)` versions and use only the one supplied with uberAgent in production.
=> Remove development code (jq version)

config-dev/Security inventory/macOS/RemoteLogin/RemoteLogin.zsh
As we talked about recently, the behavior of the macOS SCI tests should be modified to make it more consistent with the behavior on the Windows side. This PR addresses that requirement and [Martin's feedback on the SSH tests](https://podio.com/tasks/278021680).
The control flow of the updated SSH tests can be read in the `vlSshDaemonTests()` function. The most important aspect is that the tests break if SSH is disabled and no further tests are run. Another caveat is that when SSH is enabled, if the configuration is FIPS compliant, then that is understood to be a secure configuration, therefore skipping the more detailed following tests.
Either a single test score or an error is reported.
See the [test protocol](https://podio.com/uberagentcom/uberagent-dev/apps/test-protocols/items/571) …
=> Summarize the SCI SSH test results in a single test result.

config-dev/Security inventory/Windows/Firewall/Firewall.ps1, config-dev/Security inventory/macOS/Firewall/Firewall.zsh
As done with the SSH tests, aggregate the Firewall tests into a single test score to match the behavior on Windows.
Sample output:
```
[
{
"Name": "Firewallo",
"DisplayName": "Firewall status",
"Description": "Comprehensive firewall tests",
"Score": 5,
"RiskScore": 100,
"ResultData": "{
\"FirewallEnabled\":true,
\"BlockAllRuleEnabled\":false,
\"StealthModeEnabled\":false,
\"ApprovedApplications\":[\"/System/Library/CoreServices/ControlCenter.app\",\"/Applications/Docker.app\",\"/Applications/Focusrite Control.app/Contents/Library/LoginItems/FocusriteControlServer.app\",\"/System/Library/CoreServices/RemoteManagement/ARDAgent.app\"]}"
}
]
```
@martin-kretzschmar Please modify the TODO sections to match the desired wording.
See also the [updated test protocol for this SCI …
=> Aggregate all firewall tests to a single test score.

config-dev/Security inventory/macOS/Updates/Updates.zsh
Following the SCI test behavior on Windows, group dependent tests into a single test score:
- AutomaticUpdatesEnabled now includes the existing InstallSecurityResponses test into the same score.
- AutomaticDownloadEnabled and AutomaticaInstallOSUpdatesEnabled are new tests added to the AutomaticUpdatesEnabled score to make it more accurate.
- RecommendedUpdates is now a ResultData field in AutomaticUpdatesEnabled while it now also contributes to the score. In particular, when no recommended updates are available, a higher score is achieved.
For more details on the expected behavior, see the [updated test protocol](https://podio.com/uberagentcom/uberagent-dev/apps/test-protocols/items/583).
Sample output:
```
[
{
"Name": "SWUAutomaticUpdateCheckingEnabled",
"DisplayName": "macOS updates", …
```
=> macOS: Aggregate and extend the automatic OS updates tests

config-dev/Security inventory/macOS/LocalUsersAndGroups/LocalUsersAndGroups-User.zsh
This PR adds the user name to the test result for the LUUIsAdmin test to match the result display of the Windows implementation.
=> B801: align test result display with Windows implementation

config/uberAgent-meta-config.conf
This PR renames the section containing the logger options so that future options are properly stored in the correct stanza.
=> B205: rename section containing logger options

config/uberAgent-eventdata-filter.conf
Merged `develop` earlier today too fast. This was fixed in all other PRs right away but didn't land in `develop`.
=> B983: Minor link update to previous PR.

.github/workflows/Configuration.yml
Updating the configuration to check version 7.2.1 in this branch. This ensures that PRs against this branch are validated against version 7.2.1 instead of the 'develop' version.
=> Set config check version to 7.2.

config/uberAgent-data-volume-optimized.conf, config/uberAgent.conf
This pull request update the timer description for field `Interval`. It adds information about how to add a one-shot timer that is executed only once.
=> Update timer description for one-shot timers

.github/workflows/Sigma.yml
This pull request updates the `.github/workflows/Sigma.yml` workflow to simplify dependency management and remove the use of Poetry for installing `sigma-cli` and related packages. The workflow now uses pip for all Python package installations, which streamlines setup and improves maintainability.
**Dependency management simplification:**
* Removed all steps related to checking out the `sigma-cli` repository and installing dependencies with Poetry. The workflow now installs `sigma-cli` directly from PyPI using pip. [[1]](diffhunk://#diff-05312878736714b63347e85e5672064c2f4cba4fba793c594ef283bac5ae01f7L91-L97) [[2]](diffhunk://#diff-05312878736714b63347e85e5672064c2f4cba4fba793c594ef283bac5ae01f7L110-R109)
* Consolidated the installation of `pySigma-backend-uberAgent` to use pip with an …
=> 1465: Simplify Sigma workflow: remove Poetry, use pip for all Python dependencies
